### ISSUE TITLE
run test file error

### ISSUE THREAD

**Issue by Jokky6** [Vector35/idb-parser-rs#4]
when I run test file，I found error:

    --> src/lib.rs:1128:61
     |
     |                     err: Box::new(DecompressionError::Error(err)),
     |                                   ------------------------- ^^^ expected enum `TINFLStatus`, found struct `DecompressError`
     |                                   |
     |                                   arguments to this enum variant are incorrect

I'm not familiar with rust and don't know what to do with it.

rust version: rustc 1.61.0

**Comment by KyleMiles** [comment]
Sorry for the late reply here, but how are you getting this error? Running `cargo test` generates a lot of warnings for me, but no errors.

**Comment by KyleMiles** [comment]
I'm going to close this for now, but feel free to reopen it if you're still running in to this.
